### ISSUE TITLE
SSR rendering problem

### ISSUE THREAD

**Issue by jibin2706** [frankwallis/react-slidedown#17]
On SSR there is empty space between the slidedown.
Inline css is being added to the element.
In my case 
```css
{
    height: 8004.22px;
    transition-property: height;
}
```
